import { mkdir } from 'node:fs/promises'
import { join } from 'node:path'

import { resolveVersionInfo, type VersionInfo } from '@starter/version'

const root = join(import.meta.dir, '..')
const semanticVersionPattern = /^(?:v)?(\d+\.\d+\.\d+(?:-[0-9A-Za-z]+(?:[.-][0-9A-Za-z]+)*)?)$/

function option(name: string): string | undefined {
  const index = process.argv.indexOf(name)
  if (index === -1) return undefined
  const value = process.argv[index + 1]
  if (value === undefined || value.startsWith('--')) throw new Error(`${name} requires a value`)
  return value
}

function normalizeVersion(value: string): string {
  const match = semanticVersionPattern.exec(value.trim())
  if (match?.[1] === undefined) {
    throw new Error(`Expected a semantic version or v-prefixed tag, received ${value}`)
  }
  return match[1]
}

function releaseInfo(version: string): VersionInfo {
  return {
    version,
    tag: `v${version}`,
    commit: process.env['GITHUB_SHA']?.slice(0, 12) ?? 'unknown',
    dirty: false,
    source: 'environment',
  }
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === 'object' && value !== null && !Array.isArray(value)
}

async function packageManifestPaths(): Promise<readonly string[]> {
  const paths = [join(root, 'package.json')]
  for (const directory of ['apps', 'libs']) {
    const glob = new Bun.Glob('*/package.json')
    for await (const path of glob.scan({ cwd: join(root, directory), absolute: true })) {
      paths.push(path)
    }
  }
  return paths.toSorted()
}

async function updatePackageManifest(path: string, version: string): Promise<void> {
  const parsed: unknown = JSON.parse(await Bun.file(path).text())
  if (!isRecord(parsed) || typeof parsed['name'] !== 'string') {
    throw new Error(`${path} is not a package manifest with a name`)
  }
  parsed['version'] = version
  await Bun.write(path, `${JSON.stringify(parsed, null, 2)}\n`)
}

async function updateBunLock(version: string): Promise<void> {
  const path = join(root, 'bun.lock')
  const content = await Bun.file(path).text()
  const packagesMarker = '\n  "packages": {'
  const packagesIndex = content.indexOf(packagesMarker)
  if (packagesIndex === -1) throw new Error('bun.lock has no packages section')

  const workspaceSection = content.slice(0, packagesIndex)
  const packageSection = content.slice(packagesIndex)
  const versionPattern = /"version": "[^"]+"/g
  const versionEntries = workspaceSection.match(versionPattern)
  if (versionEntries === null || versionEntries.length === 0) {
    throw new Error('bun.lock has no workspace version entries')
  }

  const updatedWorkspace = workspaceSection.replace(
    versionPattern,
    `"version": ${JSON.stringify(version)}`,
  )
  await Bun.write(path, `${updatedWorkspace}${packageSection}`)
}

async function updateCargoVersion(version: string): Promise<void> {
  const path = join(root, 'Cargo.toml')
  const content = await Bun.file(path).text()
  const pattern = /(\[workspace\.package\][\s\S]*?\nversion = ")[^"]+("\n)/
  if (!pattern.test(content))
    throw new Error('Could not find [workspace.package] version in Cargo.toml')
  await Bun.write(path, content.replace(pattern, `$1${version}$2`))
}

const explicitVersion = option('--version')
const info =
  explicitVersion === undefined
    ? resolveVersionInfo()
    : releaseInfo(normalizeVersion(explicitVersion))

for (const path of await packageManifestPaths()) await updatePackageManifest(path, info.version)
await updateBunLock(info.version)
await updateCargoVersion(info.version)

const generatedPath = join(root, 'libs', 'version', 'src', 'generated.ts')
await Bun.write(
  generatedPath,
  `// Generated by tools/write-version.ts during release builds.\n` +
    `export const GENERATED_VERSION = ${JSON.stringify(info.version)}\n` +
    `export const GENERATED_TAG: string | null = ${JSON.stringify(info.tag)}\n` +
    `export const GENERATED_COMMIT = ${JSON.stringify(info.commit)}\n`,
)

const buildDirectory = join(root, 'build')
await mkdir(buildDirectory, { recursive: true })
await Bun.write(join(buildDirectory, 'version.json'), `${JSON.stringify(info, null, 2)}\n`)
console.log(`Wrote version ${info.version} from ${info.source}`)
